The default behavior of the interpreter is to execute the lines of code one after the other. However, the tools we will see in this chapter provide means for manipulating this behavior and control the "flow" of the code.

The two main categories of flow control are:

* **conditioning** the execution of specific code parts by some preliminary test
* Repeated execution of specific code parts in **loops**

# The *if* statement (and friends)

The code block within an _if_ statement will be executed only if the specified condition is fulfilled.

In [ ]:
x = 7

if x > 5:
  print("x is bigger than 5")

x is bigger than 5

In [ ]:
x = 6

if x == 5:
  print("x is equal to 5")

print("Done.")

Done.

In [ ]:
x = 80

if x >= 5:
  print("x is bigger than or equals to 5")

x is bigger than or equals to 5

In [ ]:
word = 'Scwartzenegger'

if len(word) > 10:
    print ('This is a long word...!')
if len(word) <= 10:
    print ('This word is not so long.')

print("Done!")

This is a long word...!
Done!

> **Note:** The `print("Done!")` is added to illustrate the indentation.

It should be noted that the term after the word _if_ is not necessarily a "test", but is actually a **variable**. Usually it is a Boolean variable, but we will see later that this is not necessarily the case.

In [ ]:
word = 'Schwarzenegger'

is_long_word = len(word) > 10

if is_long_word:
    print ('This is a long word...!')
if not is_long_word:
    print ('This word is not so long.')

print ("Done!")

This is a long word...!
Done!

#### Example

Print the largest number from a list of three numbers.

In [ ]:
numbers = [200, 1230, 63]

# Initializing
largest = numbers[0]

# Update
if numbers[1] > largest:
    largest = numbers[1]

if numbers[2] > largest:
    largest = numbers[2]

print(largest)

1230

## _elif_ and _else_

A series of conditions may be tested in order to choose the relevant code block, and to do that we use the _elif_ and _else_ statements. _elif_ is a short for "else if", which is used when we wish to make another optional testing. The _else_ statement does not make any more tests, but rather execute the code block it holds if no other test was True

The key point for understanding the logic of an _if...elif...else_ section is that **only the code block of the first fulfilled condition is executed**.

In [ ]:
word = 'Scwartzenegger'

if len(word) > 10:
    print ('This is a long word...!')
if len(word) <= 10:
    print ('This word is not so long.')

print("Done!")

This is a long word...!
Done!

In [ ]:
word = 'Scwartzenegger'

if len(word) > 10:
    print ('This is a long word...!')
else:
    print ('This word is not so long.')

print("Done!")

This is a long word...!
Done!

In [ ]:
age = 13

if age < 6:
    print ('I can\'t believe how much you\'ve grown.')
elif age < 18:
    print ('How\'s school?')
elif age < 90:
    print ('Let\'s have a beer!')
else:
    print ('Sooo... no teeth, ha?')

How's school?

To understand the importance of the order between the conditions, consider the implications of this order:

In [ ]:
age = 4
if age < 90:
    print ('Let\'s have a beer!')
elif age < 18:
    print ('How\'s school?')
elif age < 6:
    print ('I can\'t believe how much you\'ve grown.')
else:
    print ('Sooo... no teeth, ha?')

Let's have a beer!

**Your turn:**
1. Create a variable name 'num1' and set its value to be 10.
2. Write code with if\elif that:
    * 2.1 If the number is larger than 15 print: "The number is larger than 15"
    * 2.2 If the number is smaller than 15 print: "The number is smaller than 15"
    * 2.3 If the number is equal to 15 print: "The number is exactly 15"
3. Change the value of num1 to be 17 and run your code again - is the result correct?
4. Change the value of num1 to be 15 and run your code again - is the result correct?


5. Create a variable called 'name' and set his value to be 'Albert Einstein'
6. If the length is longer than 8 characters print "The name's length is longer than 8 characters".
7. Set name 'name' to 'Yuval' and run your code again, what is the output now?

In [ ]:
num1 = 10
if num1 >15:
  print("The number is smaller than 15")
elif num1 <15:
  print("The number is smaller than 15")
else:
  print("The number is exactly 15")

The number is smaller than 15

### Solution

In [ ]:
num1 = 15

if num1 > 15:
  print("The number is greater than 15")
elif num1 < 15:
  print("The number is smaller than 15")
# elif num1 == 15:
#   print("The number is exactly 15")
else:
  print("The number is exactly 15")

## Nested `if`

_if_ statements can be **nested** as long as we **keep our indentations correctly**.

#### Examples

In [ ]:
name = 'Yuval' # "eden"
age = 36 # 24

# if name == "Yuval" and age < 25:
if name == 'Yuval':
  print("Before nested if")
  if age < 25:
    print("Yuval is younger than 25.")
  else:
    print("Yuval is 25 years old or older.")
else:
  print("This is not Yuval")

Before nested if
Yuval is 25 years old or older.

In [ ]:
# Find the greatest number out of 3 numbers

a = 9
b = 6
c = 10

if a > b:
  if a > c:
    print('a is the greatest')
  else:
    print('c is the greatest')
else:
  if b > c:
    print('b is the greatest')
  else:
    print('c is the greatest')

c is the greatest

## [optional] Pythonic Truth

In [ ]:
list_1 = [1,2,3,4]
list_2 = []
dict_1 = {"Name": "David"}
dict_2 = {}
str_1 = "Hello!"
str_2 = ""
num_1 = 123
num_2 = 0
none_1 = None
print(type(none_1))

<class 'NoneType'>

In [ ]:
if list_1: # instead of 'if len(list_1) > 0:'
  print("Yay!")
else:
  print("Nay!")

Yay!

In [ ]:
if len(list_1) > 0: # does not empty
  print("Yay!")
else:
  print("Nay!")

Yay!

## Exercises

### Exercise 1

Create a variable 'age' and assign it with a number (any number you want).<br/>
Create a variable 'my_name' and assign it with a string (any name you want).

Print 'Correct details' if the name and age are equal to your name and age, otherwise print 'The details are incorrect'

In [ ]:
age = int(input("Age, please:"))
name = input("Name, please:").lower()
if name == "rina" and age == 24:
  print('Correct details')
else:
  print('The details are incorrect')

Age, please:24
Name, please:rina
Correct details

### Solution

In [ ]:
age = int(input("Age, please: "))
name = input("Name, please: ").lower()

if age == 28 and name == "eran":
  print("Details are correct")
else:
  print("Details are incorrect")

Age, please: 24
Name, please: Alex
Details are incorrect

In [ ]:
age = int(input("Age, please: "))
name = input("Name, please: ").lower()

if age == 28:
  if name == "eran":
    print("Details are correct")
  else:
    print("Name is incorrect")
else:
  print("Age is incorrect")

Age, please: 2
Name, please: q
Age is incorrect

### Exercise 2

Create a variable named num1 and assign it with a number (any number you want).
Print "Even" if the number is even and "Odd" if the number is odd

> **Reminder:** `n` is divisible by `d` if  `n % d == 0`

In [ ]:
num1 = int(input("Number, please:"))
if num1 % 2 == 0:
  print("Even")
else:
  print("Odd")

Number, please:23
Odd

### Solution

In [ ]:
num1 = int(input("Number, please: "))

if num1 % 2 == 0:
  print("Even")
else:
  print("Odd")

Number, please: 3
Odd

### Exercise 3 - Homework 02/07/24

Choose a number and assign it to a variable called `n`. Then write a code to check whether `n` is divisible by 2, 3 and 5 (all of them together). Is your code efficient?

In [ ]:
# My Solution if...else
num = 7
if num % 2 == 0 and num % 3 == 0 and num % 5 == 0:
  print(num, "is divisible by 2, 3, and 5")
else:
  print(num, "is not divisible by 2, 3, and 5")

7 Not divisible by 2, 3, and 5

In [ ]:
# my Solution nested if
num = 15
if num % 2 == 0:
  if num % 3 ==0:
    if num% 5 ==0:
      print(num, "is divisible by 2, 3, and 5")
else:
  print(num, "is not divisible by 2, 3, and 5")

15 is not divisible by 2, 3, and 5

In [ ]:
# my Solution if...else if...else
num = 90
if num % 2 != 0:
  print(num, "is not divisible by 2, 3, and 5")
elif num % 3 != 0:
  print(num, "is not divisible by 2, 3, and 5")
elif num % 5 != 0:
  print(num, "is not divisible by 2, 3, and 5")
else:
  print(num, "is divisible by 2, 3, and 5")

90 is divisible by 2, 3, and 5

#### Solution 1 - `if...else`

In [ ]:
if num % 2 == 0 and num % 3 == 0 and num % 5 == 0:
    print (num, "is divisible by 2, 3 and 5!")
else:
    print (num, "is NOT divisible by 2, 3 and 5!")

15 is NOT divisible by 2, 3 and 5!

#### Solution 2 - nested `if`

In [ ]:
if num % 2 == 0:
    if num % 3 == 0:
        if num % 5 == 0:
            print (num, "is divisible by 2, 3 and 5!")
        else:
            print (num, "is NOT divisible by 2, 3 and 5!")
    else:
        print (num, "is NOT divisible by 2, 3 and 5!")
else:
    print (num, "is NOT divisible by 2, 3 and 5!")

30 is divisible by 2, 3 and 5!

#### Solution 3 - `if...elif...else`

In [ ]:
if num % 2 != 0:
    print (num, "is NOT divisible by 2, 3 and 5!")
elif num % 3 != 0:
    print (num, "is NOT divisible by 2, 3 and 5!")
elif num % 5 != 0:
    print (num, "is NOT divisible by 2, 3 and 5!")
else:
    print (num, "is divisible by 2, 3 and 5!")

### Exercise 4 - Homework 02/07/24

Create a variable 'score' and assign it the number 80.<br/>
Print the score in letter-style grade (A,B,C,D,E,F) according to the following rules:

* If the score is higher than or equals to 90, print 'A'.
* If the score is higher than or equals to 80 but lower than 90, print 'B'.
* If the score is higher than or equals to 70 but lower than 80, print 'C'.
* If the score is higher than or equals to 60 but lower than 70, print 'D'.
* If the score lower than 60, print 'F'.

In [ ]:
# My Solution
score = 70
if score < 60:
  print(score, 'grade is F' )
elif score < 70:
  print(score, 'grade is D' )
elif score < 80:
  print(score, 'grade is C' )
elif score < 90:
  print(score, 'grade is B' )
else:
  print(score, 'grade is A' )

70 grade is C

#### Solution

In [ ]:
score = 80

if score >= 90:
  print("A")
elif score >= 80:
  print("B")
elif score >= 70:
  print("C")
elif score >= 60:
  print("D")
else:
  print("F")

B

### Exercise 5 - Homework 02/07/24

Create a list with 3 words of different lengths, and write a code that prints the longest word in the list.

In [ ]:
# My Solution
my_list = ['watermelon', 'apple', 'ananas']
longest_word = my_list[0]
if len(my_list[1]) > len(longest_word):
  longest_word = my_list[1]
elif len(my_list[2]) > len(longest_word):
  longest_word = my_list[2]
print('The longest word in the list is', longest_word)

The longest word in the list is watermelon

#### Solution

In [ ]:
x = ['I', 'am', 'bad']
#x = ['Python', 'is', 'cool']

longest = x[0]
if len(x[1]) > len(longest):
    longest = x[1]
if len(x[2]) > len(longest):
    longest = x[2]

print (longest)

bad

# The `for` loop

The _for_ loop enables to exeucte a specific block of code a predefined number of times, dictated by the **iterable** object on which the loop is running. Every repetition of the block of code is called **iteration**, and with each iteration the **iteration variable** is assigned a new value from the loop iterable.

## Basic Examples

In [ ]:
# [1,2,3] - iterable object
# num n - interation variable
for num in [1, 2, 3]:
    print(num)
print("Done")

1
2
3
Done

> **Note:** It is a convention that we call the iterable `i` if and only if it iterates integers. Otherwise we must use a different name!

In [ ]:
result_set = [
    ['Wendy', 32, 1.75, False],
    ['Avi', 18, 1.91, True],
    ['Dafna', 27, 1.64, False],
]

In [ ]:
for row in result_set:
  name, age, height, has_lisence = row
  if age > 20 and not has_lisence:
    print('Should send notification letter to', name)
  else:
    print('Skip sending notification letter to', name)

Should send notification letter to Wendy
Skip sending notification letter to Avi
Should send notification letter to Dafna

In [ ]:
my_list = ['Averbuch', 'Blumenfeld', 'Clementine']
for name in my_list:
    print(name)

print(my_list)

Averbuch
Blumenfeld
Clementine
['Averbuch', 'Blumenfeld', 'Clementine']

In [ ]:
for x in [('Alexandra', 23), ('Belle', 28), ('Craig', 15)]:
    print(x[0], "is", x[1], "years old")

Alexandra is 23 years old
Belle is 28 years old
Craig is 15 years old

In [ ]:
for x in [('Alexandra', 23), ('Belle', 28), ('Craig', 15)]:
    name, age = x
    print(name, "is", age, "years old")

Alexandra is 23 years old
Belle is 28 years old
Craig is 15 years old

In [ ]:
for name, age in [('Alexandra', 23), ('Belle', 28), ('Craig', 15)]:
    print(name, "is", age, "years old")

Alexandra is 23 years old
Belle is 28 years old
Craig is 15 years old

In [ ]:
values = [
    ('Alexandra', 23),
    ('Belle', 28),
    ('Creig', 15)
]

In [ ]:
for x in values:
  print(x[0], 'is', x[1], 'years old')

Alexandra is 23 years old
Belle is 28 years old
Creig is 15 years old

## The `range()` function

[`range()`](https://docs.python.org/3/library/stdtypes.html#range) is a utility function which generates an iterable sequence of integers. The full syntax allows three inputs - `start`, `stop` & `step`, where the resulted iterable iterates from `start` to `stop` (not including) in steps of `step`.

In [ ]:
for retry_counter in [1,2,3,]:
  print('This is attempt #', retry_counter)

This is attempt # 1
This is attempt # 2
This is attempt # 3

In [ ]:
for i in range(9): # alternatively for i in [0,1,2,3,4,5,6,7,8]
    print(i, end=' ') # end=' ' - in the same row

0 1 2 3 4 5 6 7 8

In [ ]:
for i in range(3, 9):
    print(i, end=' ')

3 4 5 6 7 8

In [ ]:
for i in range(3, 9, 2):
    print(i, end=' ')

3 5 7

In [ ]:
for i in range(9, 3, -2):
    print(i, end=' ')

9 7 5

#### Example

Find all the multiples of 7 from 1 to 100.

In [ ]:
for i in range(1, 101):
  if i % 7 == 0:
    print(i, end=" ")

7 14 21 28 35 42 49 56 63 70 77 84 91 98

In [ ]:
for i in range(7, 101, 7):
    print(i, end=' ')

7 14 21 28 35 42 49 56 63 70 77 84 91 98

In [ ]:
start_from = int(input('Start from number?'))
end_at = int(input('End at number?'))
adding_of = int(input('Adding of'))

for q in range(start_from, end_at+1, adding_of):
  print(q)

Start from number?5
End at number?25
Adding of2
5
7
9
11
13
15
17
19
21
23
25

> **Discussion:** In Python we have **Iterables**, **Iterators** & **Generators**. `range()` does not return a simple list, but a generator, which is out of the scope of this course. For now, all we need to know about iterators and generators is that we can (1) iterate over them, and (2) see their content with `list()` (e.g. `nums = list(range(10))`.

> **Further reading:** More about generators can be found in [Python's Wiki page about generators](https://wiki.python.org/moin/Generators) and in [Programiz](https://www.programiz.com/python-programming/generator). If you are new to Python, I would wait until learning about functions...

> **Your turn:** Create a list of words called `words`, and then iterate it and for each word print the sentence "The word _'word'_ has _x_ letters". Do it in 2 ways: by iterating the words themselves and by iterating the index of the list.

In [ ]:
# Run this cell
# My Solution 1
words = ["words", "don't", "come", "easy"]
for word in words:
  print('The word', word, 'has', len(word), 'letters' )

The word words has 5 letters
The word don't has 5 letters
The word come has 4 letters
The word easy has 4 letters

In [ ]:
# My Solution 2
for words[i] in words:
    print('The word', words[i], 'has', len(words[i]), 'letters' )

The word easy has 4 letters
The word don't has 5 letters
The word come has 4 letters
The word easy has 4 letters

In [ ]:
# My Solution 3
for i in range(len(words)):
    print('The word', words[i], 'has', len(words[i]), 'letters' )

The word easy has 4 letters
The word don't has 5 letters
The word come has 4 letters
The word easy has 4 letters

In [ ]:
# solution 1
for word in words: # more pythony, preferable solution
  print("The word", word, "has", len(word), "letters")

The word words has 5 letters
The word don't has 5 letters
The word come has 4 letters
The word easy has 4 letters

In [ ]:
# solution 2
for i in range(len(words)): # less preferable
  print("The word", words[i], "has", len(words[i]), "letters")

The word words has 5 letters
The word don't has 5 letters
The word come has 4 letters
The word easy has 4 letters

### Solution

In [ ]:
# Solution 1
for word in words:
  print("The word", word, "has", len(word), "letters.")

In [ ]:
# Solution 2
for i in range(len(words)):
    print("The word", words[i], "has", len(words[i]), "letters.")

## Initialization

Many times, each iteration will modify a common object, until finally the object will get its final form. If this is the case, then usually an initialization of the object and the relevant variables is necessary.

#### Example

Choose a number _n_ and find: <Br>
* Part A - the sum of the numbers from 1 to n <br>
* Part B - the sum of the numbers from 1 to n that are divisible by 3. <br>

In [ ]:
n = 9

##### Part A

In [ ]:
# Initialization
sum_all = 0 # defining variable and reseting variable
# Iteration
for i in range(1, n+1):
    # print(i, sum_all)
    sum_all += i  # equivalent to "sum_all = sum_all + i"
print (sum_all)

45

##### Part B

In [ ]:
# Initialization
sum_by_3 = 0
# Iteration
for i in range(1, n+1):
    if i % 3 == 0:
        sum_by_3 += i
print (sum_by_3)

18

In [ ]:
sum_by_3 = 0
# Iteration
for i in range(3, n+1, 3):
        sum_by_3 += i
print (sum_by_3)

18

> **Your turn:** Improve the solution to part B by iterating only the relevant numbers.

### Solution

In [ ]:
# Initialization
sum_by_3 = 0
# Iteration
for i in range(3, n+1, 3):
    sum_by_3 += i
print (sum_by_3)

1683

## Everyting (almost) is iterable

The fact that `for`-loops in Python can iterate the actual elements of objects is very useful. In the examples below we see that nearly all the data types and data structures we know are actually iterables.

#### Strings

The iteration is done on the characters.

In [ ]:
my_string = 'Beautiful'

In [ ]:
my_string = 'Beautiful'
for char in my_string:  # "ch" for "character"
    print (char, end=' ')

B e a u t i f u l

In [ ]:
my_string = 'Amazing'

for ch in my_string.lower():
    if ch in 'aeuio':
        print (ch.upper(), end= ' ' )

A A I

#### Lists

The iteration is done on the elements in their native order.

In [ ]:
my_list = ['Apple', 'Banana', 'Carrot', 'Fig']

for item in my_list:
    print(item, end= ' ')

Apple Banana Carrot Fig

These, of course, can be combined...

In [ ]:
my_list = ['Apple', 'Banana', 'Carrot', 'Fig']

for item in my_list:
    for char in item:
        print (char, end=' ')
    print('-->', end=' ')

A p p l e --> B a n a n a --> C a r r o t --> F i g -->

In [ ]:
# Find the max number

my_list = [1,5,4,8,9]
max_number = my_list[0]

for num in my_list:
    if num > max_number:
      max_number = num

print(max_number)

9

In [ ]:
# Find the average number

my_list = [1,5,4,8,9]
total = 0

for num in my_list:
    total = total + num

print(total / len(my_list))

# Alternatively...
print(sum(my_list) / len(my_list))

5.4
5.4

#### Tuples

Like all sequences before, the iteration is done on the elements in their native order.

In [ ]:
my_tuple = tuple(my_list)

for item in my_tuple:
    print (item, end=' ')

1 5 4 8 9

#### Dictionaries

The default iteration is through the keys

In [ ]:
my_dict = {
    'Avi': '12-Oct-1982',
    'Betty': '7-Jun-1979',
    'Carl': '31-Jan-1977',
    'David': '15-Mar-1968'
}

In [ ]:
for name in my_dict:
    print (name)

Avi
Betty
Carl
David

The iteration can also be performed through the **views** `keys()`,  `values()` and `items()`.

In [ ]:
for key in my_dict.keys():
    print (key)

Avi
Betty
Carl
David

In [ ]:
for val in my_dict.values():
    print (val)

12-Oct-1982
7-Jun-1979
31-Jan-1977
15-Mar-1968

In [ ]:
for item in my_dict.items():
    print(item)

('Avi', '12-Oct-1982')
('Betty', '7-Jun-1979')
('Carl', '31-Jan-1977')
('David', '15-Mar-1968')

In [ ]:
for item in my_dict.items():
    print ("name:", item[0], '\tBirthday:', item[1])

name: Avi 	Birthday: 12-Oct-1982
name: Betty 	Birthday: 7-Jun-1979
name: Carl 	Birthday: 31-Jan-1977
name: David 	Birthday: 15-Mar-1968

`dictionary.items()` generate a sequence of *tuples* in the form of (key, value). we can iterate over these tuples as in the example above, or we can **unpack** the tuples to different varaibles. This is another use-case where using unpacking make our code cleaner and easier to read.

In [ ]:
for item in my_dict.items():
    name, birthday = item
    print (name, '\t', birthday)

Avi 	 12-Oct-1982
Betty 	 7-Jun-1979
Carl 	 31-Jan-1977
David 	 15-Mar-1968

but we can also perform the unpacking inside the `for` loop and avoid unnecessary extra assignment

In [ ]:
for name, birthday in my_dict.items(): # preferable way - unpacking in loop definition
    print (name, '\t', birthday)

Avi 	 12-Oct-1982
Betty 	 7-Jun-1979
Carl 	 31-Jan-1977
David 	 15-Mar-1968

> **Further reading:** Although this technique is called "tuple unpacking", we can perform unpacking to any iterable object (such as lists). you can read more about tuple-unpacking in this [link][1]

[1]: https://treyhunner.com/2018/03/tuple-unpacking-improves-python-code-readability/ "tuple unpacking blog post"

#### Example

Given a sentence, create a dictionary `d_counter` of the form `{letter: count}`, where `count` is the number of occurrences of the letter in the sentence.

Notes:
* Only letters that appear in the sentence should appear in the dictionary.
* Do not make a distinction between upper-case and lower-case letters (e.g. 'a' and 'A' should be considered the same letter).
* Ignore non-letter characters. Use the string method `isalpha()` to decide whether a character is a letter or not.

In [ ]:
sentence = "God will forgive me. That's his job. (Heinrich Heine, 1797 - 1856)"

In [ ]:
# d_counter = {}
lower_sentence = sentence.lower()
characters = set(lower_sentence)

In [ ]:
print(characters)

{'f', 'r', 'c', 'd', 'w', ')', 'm', 'a', '9', 'j', 'i', 'v', ',', "'", '5', ' ', '7', 't', 'g', 'b', '(', '-', 'o', 's', '8', 'e', '1', '.', 'l', 'n', '6', 'h'}

In [ ]:
sentence = "God will forgive me. That's his job. (Heinrich Heine, 1797 - 1856)"

d_counter = {}
lower_sentence = sentence.lower()

for ch in lower_sentence:
  if ch.isalpha():
    if ch in d_counter:
      d_counter[ch] = d_counter[ch] + 1
    else:
      d_counter[ch] = 1

d_counter

{'g': 2,
 'o': 3,
 'd': 1,
 'w': 1,
 'i': 6,
 'l': 2,
 'f': 1,
 'r': 2,
 'v': 1,
 'e': 5,
 'm': 1,
 't': 2,
 'h': 5,
 'a': 1,
 's': 2,
 'j': 1,
 'b': 1,
 'n': 2,
 'c': 1}

In [ ]:
sentence = "God will forgive me. That's his job. (Heinrich Heine, 1797 - 1856)"

d_counter = {}
lower_sentence = sentence.lower()
characters = set(lower_sentence)

for ch in characters:
    if ch.isalpha():# is there letter?
        d_counter[ch] = lower_sentence.count(ch)
d_counter

{'f': 1,
 'r': 2,
 'c': 1,
 'd': 1,
 'w': 1,
 'm': 1,
 'a': 1,
 'j': 1,
 'i': 6,
 'v': 1,
 't': 2,
 'g': 2,
 'b': 1,
 'o': 3,
 's': 2,
 'e': 5,
 'l': 2,
 'n': 2,
 'h': 5}

> **Discussion:** It is not advised to change mutable object while iterating them. Consider what should be printed by the following script:
>
> ```python
> lst = ['a', 'b', 'c', 'd', 'e', 'f']
> for letter in lst:
>     print(lst.pop())
```

In [ ]:
lst = ['a', 'b', 'c', 'd', 'e', 'f']
for letter in lst:
    print(lst.pop())
    print('List after lst.pop():', lst)

f
List after lst.pop(): ['a', 'b', 'c', 'd', 'e']
e
List after lst.pop(): ['a', 'b', 'c', 'd']
d
List after lst.pop(): ['a', 'b', 'c']

## Exercises

### Exercise 1

* Print all the numbers between 1 - 10 (use range).
* Create a list named list1 with the following values: ['var1','var2','var3','var4']. Print all the values in the list.
* Create a string named srt1 with the value 'William'. Print all the letters in the string (each letter in diffrent line).
* Create list named list2 with the following values: [2,5,3,8,32,65,12,89]. Print all the numbers lower than 50.

In [39]:
# Print all the numbers between 1 - 10 (use range).
for num in range(1, 11):
  print(num, end=' ')

1 2 3 4 5 6 7 8 9 10

In [40]:
# Create a list named list1 with the following values: ['var1','var2','var3','var4']. Print all the values in the list.
list1 = ['var1','var2','var3','var4']
for values in list1:
  print(values, end=' ')

var1 var2 var3 var4

In [41]:
# Create a string named srt1 with the value 'William'. Print all the letters in the string (each letter in diffrent line).
str1 = 'William'
for letter in str1:
  print(letter)

W
i
l
l
i
a
m

In [42]:
# Create list named list2 with the following values: [2,5,3,8,32,65,12,89]. Print all the numbers lower than 50.
list2 = [2,5,3,8,32,65,12,89]
for num in list2:
  if num < 50:
    print(num, end=' ')

2 5 3 8 32 12

### Exercise 2

Create a list named list3 with the following values: [1,50,23,8,41,91,3].
Found the largest number in the list (without using the *max* function).

In [35]:
# Create a list named list3 with the following values: [1,50,23,8,41,91,3]. Found the largest number in the list (without using the max function).
list3 = [1,50,23,8,41,91,3]
max_num =0
for x in list3:
  if x > max_num:
    max_num = x
print('The max num in the list is:', max_num)

The max num in the list is: 91

### Exercise 3 - Homework 02/02/24

Write a sentence and count the number of times the letter ‘m’ appears in it using a for-loop.

In [ ]:
# My Solution
sentence = "Mammal mothers make marvelous memories for many mischievous mice."
my_letter = "m"
count = 0
for char in sentence.lower():
  if char == my_letter:
    count += 1
print("The sentence is", sentence)
print("The number of 'm' is:", count)

The sentence is Mammal mothers make marvelous memories for many mischievous mice.
The number of 'm' is: 11

#### Solution

In [ ]:
sentence = "This is my magnificent example."
my_letter = 'm'

In [ ]:
counter = 0
for letter in sentence:
    if letter == my_letter:
        counter += 1
print(counter)

3

### Exercise 4 - Homework 02/02/24

Write a sentence and do the following:

1. Count how many vowels are in it, including repetitions (e.g. ‘abracadabra’ $\rightarrow$ 5)
2. Count how many vowels are in it, without repetitions (e.g. ‘abracadabra’ $\rightarrow$ 1).

Can you do it without using sets?

In [ ]:
# 1. Count how many vowels are in it, including repetitions (e.g. ‘abracadabra’  →  5)
# My Solution including repetition
sentence = 'Mammal mothers make marvelous memories for many mischievous mice.'
vowels = ('a', 'e', 'i', 'o', 'u', 'y')
counter = 0
for char in sentence.lower():
  if char in vowels:
    counter += 1
  else:
    counter
print('The sentence', sentence, 'has', counter, 'vowels')

The sentence Mammal mothers make marvelous memories for many mischievous mice. has 24 vowels

In [2]:
# 1. Count how many vowels are in it, including repetitions (e.g. ‘abracadabra’  →  5)
# Suggested Solution including repetition
sentence = 'Mammal mothers make marvelous memories for many mischievous mice'.lower()
counter = 0
for char in 'aeiouy':
    counter += sentence.count(char)
print('The sentence', sentence, 'has', counter, 'vowels')

The sentence mammal mothers make marvelous memories for many mischievous mice has 24 vowels

In [8]:
# 2. Count how many vowels are in it, without repetitions (e.g. ‘abracadabra’  →  1)
# My solution witout repetition
sentence = 'Mammal mothers make marvelous memories for many mischievous mice'.lower()
counter = 0
for char in 'aeiouy':
  if char in sentence:
    counter += 1
print('The sentence', sentence, 'has', counter, 'unique vowels')

The sentence mammal mothers make marvelous memories for many mischievous mice has 6 unique vowels

In [10]:
# My solution witout repetition using set
sentence = 'Mammal mothers make marvelous memories for many mischievous mice'.lower()
vowels = ''
for char in 'aeiouy':
  if char in sentence:
    vowels += char
print('The sentence', sentence, 'has', len(set(vowels)), 'unique vowels')

The sentence mammal mothers make marvelous memories for many mischievous mice has 6 unique vowels

#### Solution

In [6]:
pangram = "the quick brown fox jumps over the lazy dog".lower()

> **Reference:** What is so special about the sentence [the quick brown fox jumps over the lazy dog](https://en.wikipedia.org/wiki/The_quick_brown_fox_jumps_over_the_lazy_dog)?

#### Part I

In [ ]:
# Including repetitions

counter = 0
for x in 'aeiou':
    counter += pangram.count(x)

print (counter)

#### Part II

In [7]:
# Without repetitions

# Without using sets
counter = 0
for x in 'aeiou':
    if x in pangram:
      counter += 1
print (counter)

# [optional] Using sets
vowels_letters = ''
for x in pangram:
    if x in 'aeiou':
      vowel_letters += x
print(set(vowel_letters))

5

NameError: name 'vowel_letters' is not defined

### Exercise 5 - Homework 02/02/24

Write a code that reverses a given list, where…<br/>
1. the flipped list is a new list (can you do it without using `[::-1]`?)
2. the flipping is done in-place. **(difficult)**

In [26]:
# 5. Write a code that reverses a given list, where…
#    1. the flipped list is a new list (can you do it without using [::-1]?)
# My code
my_list = ['a', 'b', 'c', [], 1, 2, 3, {}, True, False]
reverse_my_list =[]
counter = -1
for item in my_list:
  reverse_my_list.append(my_list[counter])
  counter = counter - 1
print(reverse_my_list)

[False, True, {}, 3, 2, 1, [], 'c', 'b', 'a']

In [33]:
# Suggested code
my_list = ['a', 'b', 'c', [], 1, 2, 3, {}, True, False]
reverse_my_list =[]
for item in my_list:
  reverse_my_list.insert(0, item)
print(reverse_my_list)

[False, True, {}, 3, 2, 1, [], 'c', 'b', 'a']

In [34]:
# 5. Write a code that reverses a given list, where…
#    2. the flipping is done in-place. (difficult)
my_list = ['a', 'b', 'c', [], 1, 2, 3, {}, True, False]
rev_counter = -1
counter = 0
for item in range(len(my_list)):
   my_list.append(my_list[rev_counter])
   my_list.remove(my_list[counter])
   rev_counter -= 1
   counter += 1
print(reverse_my_list)

[False, True, {}, 3, 2, 1, [], 'c', 'b', 'a']

#### Solution

##### Part 1

In [32]:
my_list = ['a', 'b', 'c', [], 1, 2, 3, {}, True, False]
flipped = []

for el in my_list:
    flipped.insert(0, el)

print(flipped)

[False, True, {}, 3, 2, 1, [], 'c', 'b', 'a']

##### Part II

Note that this solution changes _my\_list_ during iteration, which is a bad practice (but is safe in this case).

In [30]:
my_list = ['a', 'b', 'c', [], 1, 2, 3, {}, True, False]

for i in range(len(my_list)):
    my_list.insert(0, my_list.pop(i))

print (my_list)

[False, True, {}, 3, 2, 1, [], 'c', 'b', 'a']

```
Illustrating how the code above works:

  0      1      2      3
"aaa", "bbb", "ccc", "ddd"

i = 0
"bbb", "ccc", "ddd" ("aaa") <-- pop-ed
"aaa", "bbb", "ccc", "ddd"

i = 1
"aaa", "ccc", "ddd" ("bbb")
"bbb", "aaa", "ccc", "ddd"

i = 2
"bbb", "aaa", "ddd" ("ccc")
"ccc", "bbb", "aaa", "ddd"

i = 3
"ccc" "bbb", "aaa" ("ddd")
"ddd", "ccc", "bbb", "aaa"
```

### Exercise 6 - Homework 02/02/24

1. Create a dictionary with 10 items of the form {name: age}.
2. Calculate the average age of the people in the dictionary.

In [24]:
my_dict = {
    'Avi': 15,
    'Betty': 24,
    'Carl': 5,
    'David': 30
}
total = 0
for age in my_dict:
    total = total + my_dict[age]
print('The average age is', total / len(my_dict))

# Alternatively...
print('The average age is', sum(my_dict.values()) / len(my_dict))

The average age is 18.5
The average age is 18.5

#### Solution

In [ ]:
tribes = {
    'Reuven': 23, 'Simeon': 34, 'Levi': 51, 'Judah': 36,
    'Dan': 36, 'Naphtali': 25, 'Gad': 36, 'Asher': 27,
    'Issachar': 41, 'Zebulun': 19, 'Joseph': 24, 'Benjamin': 28
}

In [ ]:
sum_of_ages = 0

for age in tribes.values():
    sum_of_ages += age

average_age = sum_of_ages / len(tribes)

print(average_age)

# The _while_ loop

The `while` statement executes a block of code as long as a specified **iteration condition** is fulfilled. Unlike the `for` loop, it does not utilize an iteration variable, but rather depends on the results during the execution of the code, which may change the truth value of the iteration condition. The `while` loop is specifically useful when the theoretical number of iterations is infinite or unknown.

It is very often a confusing matter to apply the `while` loop properly, and below are some things to consider when implementing such a loop:

* The "testing" of the iteration condition happens `before` any iteration is executed. That includes the first iteration.
* If nothing is changed inside the loop, then the condition will never be fulfilled, and the loop will run infinitely.
* One of the vulnerabilities of `while` loops are the **edge cases**. Deal with them carefully.

### Example

In [ ]:
number = 1

while number < 10:
    number += 1
    print(number)

print('end')

In [ ]:
number = 1

while number != 10:
  print(number)
  number += 2

## Exercises

### Exercise 1

Summing the integers from 1 (1, 2, 3...), at which integer the sum will exceed 1000?

#### Solution

In [ ]:
i = 0
sum_of_nums = 0
while sum_of_nums <= 1000:
    i += 1
    sum_of_nums += i
print ("The number is", i)

# [optional] Skipping iterations

There are situations in which you wish to skip an iteration or even completely terminate the loop, and this behavior can be achieved by two special words:

* **continue** will quit the current iteration and start the next one.
* **break** will terminate the entire loop and proceed with the outer code execution.

The following should be noted for both statements:

* They are applicable only within a _for_- or a _while_-loop. Otherwise an error will be raised.
* They refer only to the inner-most loop in which they are called.
* They can be used within infinte loops as well

### Basic examples

The following code will print the letters of the word 'Python' which are not vowels.

In [ ]:
for letter in "Python":

    if letter == 't':
        continue

    print(letter)

print("end")

The following code will print the letters of the word 'Python' **until** it reaches a vowel.

In [ ]:
for atomic_missile in "Python":

    if atomic_missile in 'aeiou':
        break

    print (atomic_missile, end=' ')

The following code will do the following for each word in the sentence:

* If the letter 'r' is in the word, it will do nothing
* If the letter 'r' is not in the word, then letters of the word will be printed until the letter 'n' (if exists), and then it will show the original word.

In [ ]:
sentence = "Continue and break are useful"
for word in sentence.split():
    if 'r' in word:
        continue
    for letter in word:
        if letter == 'n':
            break
        print (letter, end=' ')
    print ("-", word)

In [ ]:
sentence = "Continue and break are useful"
print(sentence.split())

In [ ]:
for ch in sentence:
    print(ch, end = ' ')

### Example

Make the list of all the numbers between 1 and 1000 that are divisible by **all of** 6, 15 & 35.

In [ ]:
good_numbers = []

for i in range(1, 1001):
    if i % 6 != 0:
        continue
    if i % 15 != 0:
        continue
    if i % 35 != 0:
        continue
    # if you made it to here,
    # then you are divisible by all the numbers
    good_numbers.append(i)

print (good_numbers)

In [ ]:
good_numbers = []
for i in range(1, 1001):
    if i % 6 == 0 and i % 15 == 0 and i % 35 == 0:
        good_numbers.append(i)
print (good_numbers)

In [ ]:
good_numbers = []
for i in range(1, 1001):
    if (i % 6 == 0 and i % 15 != 0 and i % 35 != 0) or \
       (i % 6 != 0 and i % 15 == 0 and i % 35 != 0) or \
       (i % 6 != 0 and i % 15 != 0 and i % 35 == 0):
        good_numbers.append(i)
print (len(good_numbers), good_numbers)

In [ ]:
good_numbers = []
for i in range(1, 1001):
    if (i % 6 == 0 and i % 15 != 0 and i % 35 != 0) or (i % 6 != 0 and i % 15 == 0 and i % 35 != 0) or (i % 6 != 0 and i % 15 != 0 and i % 35 == 0):
        good_numbers.append(i)
print (len(good_numbers), good_numbers)

> **Your turn:** Find all the numbers between 1 and 100 that are divisible by **at least one of** 6, 15 & 35.

### Solution

In [ ]:
numbers = []

for num in range(1, 101):
  if num % 6 == 0 or num % 15 == 0 or num % 35 == 0:
    numbers.append(num)

numbers

In [ ]:
numbers = []

for num in range(1, 101):

  if num % 6 == 0:
    numbers.append(num)
  elif num % 15 == 0:
    numbers.append(num)
  elif num % 35 == 0:
    numbers.append(num)

numbers

> **Your turn (bonus):** All the numbers between 1 and 100 that are divisible by **exactly one of** 6, 15 & 35.

## Exercises

### Exercise 1

Summing the integers from 1 (1, 2, 3...), at which integer the sum will exceed 1000? Use a *for loop* this time.

#### Solution

In [ ]:
sum_of_nums = 0

for i in range(1, 100):
    sum_of_nums += i
    if sum_of_nums > 1000:
        print ("The number is", i)
        break

### Exercise 2

Find the first number that is divisible by 2, 10 , 7,  5 (all of them).

#### Solution

In [ ]:
num = 0
is_divisible = False

while not is_divisible:
  num = num + 1
  if (num % 2 == 0) and (num % 10 == 0) and (num % 5 == 0) and (num % 7 == 0):
    is_divisible = True

print(num)